### ISSUE TITLE
Crach CE5 - CEVPlayer

### ISSUE THREAD

**Issue by zmod3535** [afrostalin/CEVPlayer#3]
[editor.log](https://github.com/afrostalin/CEVPlayer/files/4307885/editor.log)

During testing during the game in the editor, the SDK crashes, but this does not happen all the time.
Failure occurs when esc I press before completing testing the video plugin.

**Comment by afrostalin** [comment]
Hello, thank you for reporting.
Fixed in https://github.com/afrostalin/CEVPlayer/releases/tag/v.1.0.0.5
