### ISSUE TITLE
CEVPlayer in GameSDK  player issue

### ISSUE THREAD

**Issue by MatrixHan** [afrostalin/CEVPlayer#5]
my  use  it  at  GameSDK5.6  startgame  after ,  texture  nodraw .  after   physice  collision  target  draw  it.

**Comment by MatrixHan** [comment]
about CTextureVideoPlayerComponent

**Comment by afrostalin** [comment]
Hello. Can you provide full list actions for repeat this issue? 
Thanks

**Comment by MatrixHan** [comment]
https://user-images.githubusercontent.com/8830181/116036495-62a32c00-a699-11eb-890c-ce45e9d3a51a.mp4

this video  list actions.

**Comment by MatrixHan** [comment]
oh  my no add environment prob ,  this  issue  fix.
